#!/usr/bin/python
#! encoding:utf-8

import sys
import os
import re
import serial
import binascii
import time
import json

#os.system("ls /dev | grep '^ttyUSB'")
tmp = os.popen("ls /dev | grep '^ttyUSB'").readlines()
print "Content-Type: application/json"
print ""
print "{"
content=""
for tty in tmp:
    #print(tty)
    ttyname=tty.strip('\n')
    #print(ttyname)
    for i in [ 115200,9600,  128000, 256000, 57600,56000,38400,19200,14400,4800,2400]:
        #print("/www/cgi-bin/blockly_info/"+ttyname)
        ser = serial.Serial("/dev/"+ttyname, i, timeout=3)
        ser.open()
        ser.write("\x48\x59\x3c\x00\x00\x00")
        aa=ser.readline()
        #print(aa)
        #hexShow(aa)
        if aa=="test\r\n":
            rate=i
            break
        else:
            time.sleep(1)
            ser.close()    
    else:
        print('no match')
        exit(0)
    info = open("/www/cgi-bin/blockly_info/"+ttyname, "w")
    ser.write("\x48\x59\x3c\x00\x0a\x0a") 
    aa=ser.readline()
    jsonresult=json.loads(aa)
    #print(jsonresult["Name"])
    #info.write("rate:"+str(i)+"\r\n")   
    while aa<>'':
    #hexShow(aa)
        info.write(aa)
        aa=ser.readline() 
    #hexShow('/n')    
    ser.close()
    info.close()    
        #print "update the file:"+i.strip('\n')
    content+='\"'+str(jsonresult["Name"])+'\":{\"tty\":\"'+ttyname+'\",\"baud\":\"'+str(rate)+'\"},'
    #content+='''%s:{tty:%s,baud:"%h"},'''%(str(jsonresult["Name"]),ttyname,rate)
info2= open("/www/cgi-bin/blockly_info/intiinfo", "w")
if     not content.strip():
    print "}"
    info2.write("{}")
else:
    info2.write("{")
    info2.write(content[0:-1])
    info2.write("}")
    print content[0:-1]
    print "}"
info2.close()
