#!/usr/bin/python
#! encoding:utf-8
# Filename : socket_echo_udp_server_dgram.py
# import socket
import sys
import serial

# open serial port
ser = serial.Serial("/dev/ttyACM0", 115200, timeout=0.005)
ser.open()
ser.write("\x48\x59\x3c\x02\x0C\x0D\x01\x00")   
print "Content-Type: application/json"
print ""
print "{}"
ser.readline()
ser.close