#!/usr/bin/python
#! encoding:utf-8
import sys
import os
import urllib
tmp = os.popen("ls /www/blockly/xml | grep '.xml$'").readlines();
print "Content-Type: application/json";
print "";
sys.stdout.write("{");
i=0;
content=""
for x in tmp:
#    print(x)
    #name=x.split('_')
    content=content+'"name'+str(i)+'":"'+x[0:-1]+'",';
    i=i+1;
print(content[0:-1]+'}')

