#!/usr/bin/python
#! encoding:utf-8
import sys
import os
import cgi
import urllib
print "Content-Type: application/json\n"
form = cgi.FieldStorage()
if form.has_key("deleteName") and form["deleteName"].value != "":
    os.system("rm /www/blockly/xml/"+form["deleteName"].value)
    print''' {"result":"rm /www/blockly/xml/%s"}'''%form["deleteName"].value
else:
    print '''{"result":"error"}'''