#!/usr/bin/python
#! encoding:utf-8
import sys
import os
import cgi
import urllib
print "Content-Type: application/json\n"
form = cgi.FieldStorage()
if form.has_key("loadName") and form["loadName"].value != "":
    file_path="/www/blockly/xml/"+form["loadName"].value
    info = open(file_path, "r")
    xml=info.read()
    info.close()
    print''' {"result":"success","xml":"%s"}'''%urllib.quote(xml)
else:
    print '''{"result":"error"}'''