#!/bin/sh

ussid=''
upass=''
if [ -n "$QUERY_STRING" ]; then
    echo "Content-Type: application/json"
    echo ""
	firstexp=`echo $QUERY_STRING | cut -d'&' -f 1`
	firstkey=`echo $firstexp | cut -d'=' -f 1`
	firstvalue=`echo $firstexp | cut -d'=' -f 2`

	secondexp=`echo $QUERY_STRING | cut -d'&' -f 2`
	secondkey=`echo $secondexp | cut -d'=' -f 1`
	secondvalue=`echo $secondexp | cut -d'=' -f 2`

	if [ "$firstkey"x = "ssid"x ] && [ "$secondkey"x = "password"x -o "$secondkey"x = "passwd"x ]; then
		ussid=$firstvalue
		upass=$secondvalue
	elif [ "$secondkey"x = "ssid"x ] && [ "$firstkey"x = "password"x -o "$firstkey"x = "passwd"x ]; then
		ussid=$secondvalue
		upass=$firstvalue
	else
		echo "{\"result\"=\"error\",\"message\"=\"Please input the right format like ssid=xxxx&passwd=yyyy\"}"
		exit 1
	fi
   	
elif [ -z "$1" -o -z "$2" ]; then
    	echo "Need to specify ssid and password, like setwifi ssid password"
    	exit 2
else
    	ussid=$1
    	upass=$2
fi
iwpriv ra0 set SiteSurvey=0
OUTPUT=`iwpriv ra0 get_site_survey | grep '^[0-9]'` 
while read line
do
	ssid=`echo $line | awk '{print $2}'`
	if [ "$ssid"x = "$ussid"x ]; then
# 	# Set interfaces file
		umode=""
		uencryp=""

		chanel=`echo $line | awk '{print $1}'`
		security=`echo $line | awk '{print $4}'`


		if [ "$security"x = "WPA1PSKWPA2PSK/TKIPAES"x ]; then
			umode="WPA2PSK"
        		uencryp="AES"
		elif [ "$security"x = "WPA1PSKWPA2PSK/AES"x ]; then
			umode="WPA2PSK"
        		uencryp="AES"
		elif [ "$security"x = "WPA2PSK/AES"x ]; then
        		umode="WPA2PSK"
        		uencryp="AES"
  	  	elif [ "$security"x = "WPA2PSK/TKIP"x ]; then
        		umode="WPA2PSK"
	        	uencryp="TKIP"
   		elif [ "$security"x = "WPAPSK/TKIPAES"x ]; then
        		umode="WPAPSK"
	        	uencryp="TKIP"
		elif [ "$security"x = "WPAPSK/AES"x ]; then
   			umode="WPAPSK"
        	uencryp="AES"
		elif [ "$security"x = "WPAPSK/TKIP"x ]; then
    		umode="WPAPSK"
        	uencryp="TKIP"
		elif [ "$security"x = "WEP"x ]; then
    		umode="WEP"
        	uencryp="WEP"
   		fi

		uci set wireless.ra0.channel=$chanel
		uci set wireless.@wifi-iface[0].ApCliSsid=$ussid
		uci set wireless.@wifi-iface[0].ApCliPassWord=$upass
		uci set wireless.@wifi-iface[0].ApCliAuthMode=$umode	
		uci set wireless.@wifi-iface[0].ApCliEncrypType=$uencryp
		uci commit

# 		# Restart network service
 		/etc/init.d/network restart 1>&- 2>&-

		apcli=`ifconfig | grep apcli0`
		while [[ -z "$apcli" ]]
		do
			apcli=`ifconfig | grep apcli0`
		done

		sleep 20
		ip=`ifconfig apcli0 | grep 'inet addr:'| cut -d: -f2 | awk '{ print $1}'`
		if [ $ip ]; then
			echo "{\"result\":\"success\",\"message\":\"connected to $ussid with IP $ip\"}"
		else
			echo "{\"result\":\"error\",\"message\":\"can not connect to $ussid\"}"
		fi

        exit 0
    fi
done <<EOF
$OUTPUT
EOF

echo "{\"result\":\"error\",\"message\":\"can not find WIFI with ssid $ussid\"}"
exit 3
