#!/bin/sh

case "$ACTION" in 
	add)
		for i in $(ls /dev/ | grep 'sd[a-z][1-9]')
			do
				#mkdir -p /mnt/$i
				ntfs-3g /dev/$i /mnt
				#/etc/init.d/aria2 restart
			done 
		;;
	remove)
		MOUNT=`mount | grep -o '/mnt/sd[a-z][1-9]'`

		for i in $MOUNT
			do
				umount /mnt
				#rm -r $i
				#/etc/init.d/aria2 stop
			done 
		;;
esac
