#!/usr/bin/python
#! encoding:utf-8
# Filename : socket_echo_udp_server_dgram.py
# import socket
import sys
import serial
import binascii
import time
import cgi
def hexShow(argv):  
    result = ''  
    hLen = len(argv)  
    for i in xrange(hLen):  
        hvol = ord(argv[i])  
        hhex = '%02x'%hvol  
        result += hhex+' '  
    print 'result:',result
def hexreturn(argv):  
    result = ''  
    hLen = len(argv)  
    for i in xrange(hLen):  
        hvol = ord(argv[i])  
        hhex = '%02x'%hvol  
        result += hhex+' '  
    return(result)
def getcheck(argv):  
    result =0
    hLen = len(argv)
    for i in xrange(hLen-4):
        hvol = ord(argv[i+4]) 
        result=result^hvol
    result=unichr(result)
    return(result)
print "Content-Type: application/json\n"
info = open("/tmp/car_log", "aw")  
ser = serial.Serial("/dev/ttyS0", 57600, timeout=0.2)
ser.open()
sel="$M<\x00f"
chechnum=getcheck(sel)
sel=sel+str(chechnum)
ser.write(sel)
strc=ser.read(7)
top ="\x24\x4d\x3e"
nPos = strc.find(top)
if nPos==0 and len(strc)==7:
    ans=ord(strc[nPos+5])
else:
    ans=2
    info.write(str(len(strc))+"   "+str(nPos)+'\n')
ser.readline()
ser.close
info.write(hexreturn(strc)+'\n')
info.close
print '''{"result":"success","ans":"%d"}'''%ans